name: Dependency policy

on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: "23 8 * * 1"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: dependency-policy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cargo-deny:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: EmbarkStudios/cargo-deny-action@3c6349835b2b7b196a839186cb8b78e02f7b5f25 # v2.1.1
        with:
          command: check
          arguments: --all-features
